### ISSUE TITLE
add command to remove image ?

### ISSUE THREAD

**Issue by skramm** [arnellebalane/imgur-upload-cli#5]
Great tool ! 
This is a feature request: it would be great to be able to have an command to **remove** an image that has been uploaded.
Of course, this would imply to be authenticated (so you can only remove images that your account has uploaded), and I agree that would add some complexity.
So probably related to https://github.com/arnellebalane/imgur-upload-cli/issues/2

What do you think ? Doable ?

**Comment by arnellebalane** [comment]
@skramm thanks 😃 

Your feature request is doable even without having to authenticate the user (#1 ), and will also be possible when #2 is done.

Will resume work on this project real soon, thanks for checking this out 👍 Feel free to submit PRs as well if you want 🎉

**Comment by arnellebalane** [comment]
@skramm Removing an uploaded image from imgur is now available as of `v1.1.0` of this package. Please update your version accordingly. Thanks for your request! 👍
